### ISSUE TITLE
bug(YouTube/Hide shorts components): hide shorts toolbar not working

### ISSUE THREAD

**Issue by thotsprayer** [inotia00/ReVanced_Extended#1757]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Yt v18.45.43

### Bug description

So when I tried Hiding Camera button or Search or menu on shorts its not hiding
I'm using the latest patches (v2.201.1)

### Solution

I don't even know, I just need help

### Additional context

The full shorts toolbar not hiding even when I hide them in the settings and restarting the app

### Device Environment

Android 13, MUI 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
please upload screenshot

**Comment by thotsprayer** [comment]
Screenshot of what ?, I mean what you want to screenshot the camera button didn't hide when I turn it off in the settings that it

**Comment by thotsprayer** [comment]
![Screenshot_2023-11-29-21-00-30-312_app rvx android youtube~2](https://github.com/inotia00/ReVanced_Extended/assets/149886103/ad354a08-1bf6-4c19-bbb6-ba80714a0df7)
![Screenshot_2023-11-29-21-00-17-612_app rvx android youtube~2](https://github.com/inotia00/ReVanced_Extended/assets/149886103/7b9341e1-c51a-4b08-bb47-4a574a1819eb)

**Comment by inotia00** [comment]
are you using the `Spoof app version`?

**Comment by thotsprayer** [comment]
No

**Comment by inotia00** [comment]
This issue does not reproduce for me

**Comment by inotia00** [comment]
The bug is not reproduced and everything works fine for me.

**Comment by thotsprayer** [comment]
I know I've asked people in reddit and they say that is work fine for them And I'm confused Like why this happens what should I do please any advice ???

**Comment by inotia00** [comment]
Bugs that cannot be reproduced by developers cannot be fixed.

The reason you are opening an issue here is simply to get advice for others experiencing the same bug.

**Comment by thotsprayer** [comment]
I was thinking of Installing RVX for a github page called NoName or something is that good

**Comment by inotia00** [comment]
nah it's an illegal build
RVX does not distribute prebuilt APKs

**Comment by thotsprayer** [comment]
ok, but I downloaded it to try and its working finally the camera button turned off, its working on it but not when I tried to patch it myself I'm just wondering and what you by its illegal

**Comment by inotia00** [comment]
ReVanced only provides core code and patch tools, and shifts all patching processes to the user. pre-built APK is not provided.

This is to avoid repeating the mistake TeamVanced made - receiving threats from Google for distributing pre-built APKs - and by sticking to this ideology, the project was able to continue without being discontinued for over a year.

Distributing a prebuilt APK may lead to discontinuation of the project, Just like TeamVanced did.

Therefore, ReVanced Team and RVX never distribute any prebuilt APKs.
This is why all websites distributing prebuilt APKs are treated as ‘illegal’
(May lead to risk of discontinuation of the entire project)

Anyway, the issue appears to have been resolved, so I will close it.

**Comment by thotsprayer** [comment]
thanks for Explaining, but wait what are you talking about the issue is not resolved on the main rvx app just on the prebuild Apk. This is misleading my dude ! I need response

**Comment by thotsprayer** [comment]
So anyways I I have an update : So I uninstalled RVX completely and I downloaded a new apk and I patched it And its finally working great the issue has fixed but I still need a response why? why I was have to Uninstall the apk completely like its annoying now I have to setup all my settings once again. I just want to know why it cost All of this ?

**Comment by inotia00** [comment]
I'm sorry, but this is not a community for discussion.

The purpose of this repo is to share the symptoms of bugs, the process of reproducing bugs, the proper screenshot, and the workaround you found with others.

All comments written in this repo send github notifications, e-mail notifications to all users registered as a collaborator, as well as the mainainer of repo.
Therefore, do not leave unnecessary comments if possible.

Please open a new issue while satisfying the conditions listed above.
