### ISSUE TITLE
bug: Likes/Dislikes not Showing as Number or Procentage

### ISSUE THREAD

**Issue by 30b0** [inotia00/ReVanced_Extended#2419]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.16.39 | Patches v4.14.2-dev.2

### Bug description

The Like/Dislike Number (or Number as Percentage) isn't showing anymore.
I tested it with all default Settings after Patching and the Problem is still there. Another Account has the same Problem.

Even with Return Dislikes disabled the Likes Number isn't showing anymore.

Tested it again with a clean install of YouTube RVX 

This happend with the dev.2-Patches, dev.1 hasn't had that Problem.

![Screenshot_20241004-144001_YouTube](https://github.com/user-attachments/assets/3ff33a1b-6e72-4153-808c-17652c513712)
![Screenshot_20241004-155156_YouTube](https://github.com/user-attachments/assets/df31d321-f521-4576-8a44-bfc5e1bec3cb)
![Screenshot_20241004-155225_YouTube](https://github.com/user-attachments/assets/bf4a5a1f-90ab-4159-a8b9-708d1f9c178d)

### Solution

**Spoof app version to 18.48.39,**

### Device Environment

Android 14, CrDroid 10.8, OnePlus 9 Pro, Rooted with Magisk 27.0

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by 30b0** [comment]
Used Settings as File, SB-Id was delted.

[Uploading YT_RVX.txt…]()

**Comment by inotia00** [comment]
The main change in dev.2 is in `Spoof streaming data`

1. Can the issue be reproduced even if `Spoof streaming data` is turned off? (in dev.2)
2. Can the issue be reproduced even if you patch to the main branch (with Pre-releases turned off) and then update?

**Comment by 30b0** [comment]
1. Disabling "Spoof streaming data" didn't change anything, likes are still hidden.
2. Clean installed Patches 1.14.1 again and the Problem is also there, that wasn't the Case last Time with the same Patches... Updating with 1.14.2-dev.2 Patches didn't change the Situation.

The unpatched YouTube App shows the Likes, as soon as it's patched that isn't the Case anymore. Even in the Description Views, Likes and upload Date aren't shown anymore.
![Screenshot_20241004-165611_YouTube](https://github.com/user-attachments/assets/6c243fdf-c164-4128-b2d0-f4175aca41fb)

**Comment by inotia00** [comment]
If so, I think this is most likely A/B tests

It is not reproducible on my side

If you have time, I would appreciate it if you could also test the following two

1. Include only `Gmscore support` patch and exclude all other patches

Patch YouTube 19.16.39 and see if the issue persists

2. Include all patches with default values ​​and patch YouTube 19.05.36

**Comment by inotia00** [comment]
> Used Settings as File, SB-Id was delted.
> 
> Uploading YT_RVX.txt…

The file was not uploaded correctly

Please re-upload the file or upload it as text

**Comment by 30b0** [comment]
Same Problem with only the Icon Patched on 19.16.39 and all other Patches were excluded.

**Comment by 30b0** [comment]
It's working with 18.48.39 with the same Patches and imported Settings attached above.
![Screenshot_20241004-174200_YouTube](https://github.com/user-attachments/assets/7360cb79-b432-4459-bb10-24d305be7ab2)
![Screenshot_20241004-174217_YouTube](https://github.com/user-attachments/assets/7fc7e3b3-897c-4ddc-a97b-b396d0835b7d)

**Comment by Cast0r-999** [comment]
I have same bug!!! No likes/dislikes, no views numbers. Main + brand account. Stable patches.

**Comment by inotia00** [comment]
No matter how much I think about it, this can only be an issue on the YouTube side

1. The issue is reproduced even if OP turns off Spoof streaming data
2. The issue is reproduced even if OP includes only the GmsCore support patch and excludes the rest of the patches
3. The same result is obtained even in the main branch where no major changes have been applied
4. There is no issue in YouTube 18.48.39, the only version where rolling numbers are not applied on the server side

**Comment by inotia00** [comment]
The only workaround so far is to re-patch YouTube to 18.48.39
Or spoof app version to 18.48.39

**Comment by 30b0** [comment]
Spoofing the Version 18.48.39 works without Problems.

ReVanced Users are having the same Problem, maybe they'll find something, if it's really a ReVanced Problem: https://github.com/ReVanced/revanced-patches/issues/3741

**Comment by 30b0** [comment]
The Problem isn't there anymore with the v4.15.1-dev.1 Patches after updating it from the v4.14.1-dev.2 Patches!

**Comment by Cast0r-999** [comment]
For me, last dev. 15.1 patch did not help.

**Comment by 30b0** [comment]
Edit to my last Comment, it worked for about 1 1/2 Days, now I have to spoof 18.48.39 again to get it working...

**Comment by Cast0r-999** [comment]
Temporal solution: spoof app version to 19.12.41

**Comment by inotia00** [comment]
This is a bug in YouTube, not in RVX

Instead, you can fix the issue with `Spoof app version`

As far as I know, spoofing with YouTube 19.13.37 works

**Comment by andris155** [comment]
I have same a problem in the v19.16.39. I updated to the v19.31.36 and this is fixed the problem. Revanced not recommend and supported this version but for me works perfectly fine.

**Comment by inotia00** [comment]
When the default value of the `Spoof app version` is ON, the library shelf sub-components are hidden under certain conditions

The default value of the `Spoof app version` should be OFF

**Comment by inotia00** [comment]
reflected in [revanced-patches-4.15.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.15.1)

**Comment by AntarCrypto** [comment]
It's not showing again 
Please how to fix it 
I turned off spoof app version still not showing

**Comment by Derfboy** [comment]
I'm having the same issue. Can't spoof to less than v19.x.x.
