### ISSUE TITLE
bug(YouTube - Remove background playback restriction): Play/Pause button not working in PiP mode

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#2764]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube v19.44.39

### Bug description

At times, the Play/Pause button stops working when playing in PiP mode and when opening the app and going back to PiP fixes it sometimes.

https://github.com/user-attachments/assets/45884602-b89a-472f-aea3-00728ad86d35

### Error logs

```shell

```

### Acknowledgements

- [x] This issue does not reproduce on unpatched YouTube or YT Music.
- [x] This issue is not a duplicate of an existing bug report.
- [x] I did not use any settings marked as `Experimental Flags`.
- [x] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] I have written the title and contents in English.

**Comment by esperanzality** [comment]
me too

**Comment by melaqa** [comment]
Me too, but I find that if I use Youtube 19.16.39 With the latest patch (5.4.1 Dev 3). This problem won't happen.

**Comment by inotia00** [comment]
### Additional context

This bug is reproduced under certain conditions.

Reproduce step is the same as https://github.com/ReVanced/revanced-patches/issues/4168.

1. `Remove background playback restriction` patch is included.
2. `Disable Shorts background play` is off (In the case of ReVanced, `Restore old settings menus` must be off).
3. Log in as non-premium account.
4. Open the video.
5. Go to the comment section.
6. Click 'N more replies' that contains time stamps.
7. Click time stamp.
8. Click the back button of the toolbar.
9. Click the home button to switch to PIP mode.
10. Bug occurs.

Unlike https://github.com/ReVanced/revanced-patches/issues/4168, this bug is not reproduced in unpatched YouTube.

(In unpatched YouTube, PiP mode is not provided to a non-premium account)

**Comment by inotia00** [comment]
There are two ways to reproduce this issue.

The first way to reproduce the issue is mentioned in the [previous comments](https://github.com/inotia00/ReVanced_Extended/issues/2764#issuecomment-2632970519).

→ **This seems to be a bug in the patched RVX, so it's going to be a fix.**

Here is the second way to reproduce the issue:

1. Play the video and switch to PiP mode.
2. Turn off the screen, then turn it back on.
3. Bug occurs.

→ **This can also be reproduced on unpatched YouTube, so Google should fix it.**

**Comment by melaqa** [comment]
This issue still occurs with the latest patch (5.4.1 dev 4).

**Comment by inotia00** [comment]
> This issue still occurs with the latest patch (5.4.1 dev 4).

There are two ways to reproduce this bug.

One is only reproduced on RVX, the other is reproduced on both RVX and YouTube.

The bug that reproduces only on RVX has been fixed in 5.4.1-dev.4.

The bug that reproduces on unpatched YouTube is not a bug in RVX, but a bug in YouTube, so Google should fix it.

**Comment by inotia00** [comment]
Issue closed as this is a reproducible bug even on unpatched YouTube

(Tested on unpatched YouTube 19.44.39 with a YouTube Premium account, Google should fix it)

**Comment by ILoveOpenSourceApplications** [comment]
Just for clarity, the bug which occurs without locking the screen is also reproducible on unpatched YouTube with a YouTube premium?

**Comment by inotia00** [comment]
Even if I exclude all patches and include only the `GmsCore support` patch, the issue is reproduced

I don't think it's an issue with the `Remove background playback restriction` patch

**Comment by ILoveOpenSourceApplications** [comment]
Got it. Well, here's hoping YouTube will fix this.

**Comment by twinko** [comment]
The fix is to change the player stile to minimal

settings>ReVanced>Player>Mini Player.
