### ISSUE TITLE
bug:(YouTube - Video player): `Disable 1080p Premium Menu` not working

### ISSUE THREAD

**Issue by Mehedi5585** [inotia00/ReVanced_Extended#3113]
### Type

Error at runtime

### Tools used

CLI

### Application

YouTube v19.47.53

### Bug description

![Image](https://github.com/user-attachments/assets/06d4dd54-dbee-4ca2-ba98-e79385eef3b4)

### Error logs

```shell

```

### Acknowledgements

- [x] This issue does not reproduce on unpatched YouTube or YT Music.
- [x] This issue is not a duplicate of an existing bug report.
- [x] I did not use any settings marked as `Experimental Flags`.
- [x] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] I have written the title and contents in English.

**Comment by inotia00** [comment]
This issue doesn't reproduce on my side.

So even if I try to fix it, I can't be sure it's fixed.

**Comment by inotia00** [comment]
It was probably fixed in [revanced-patches-5.10.1-dev.2](https://github.com/inotia00/revanced-patches/releases/tag/v5.10.1-dev.2), but I'm not sure.

**Comment by Mehedi5585** [comment]
> It was probably fixed in [revanced-patches-5.10.1-dev.2](https://github.com/inotia00/revanced-patches/releases/tag/v5.10.1-dev.2), but I'm not sure.

Bro Not working

**Comment by ExoAis** [comment]
@inotia00 The playback error while playing the audio on RVX Music is still arising even after spoofing client and video streams. Just like how every video failed to run with an error code shown on the screen a fews ago, this suddenly started happening just now again.

But after disabling 'Spoof Client' option while keeping 'Spoof Video Streams' enabled, the issue is gone. The playback doesn't pose any problem as well. That means the Spoof Client is the issue.

**Comment by Mehedi5585** [comment]
https://github.com/user-attachments/assets/7ca882a8-ac26-4808-b7be-e0d647249cec

It's not Solved, it's the same as before. I'm using CLI Pc not rvx manager

**Comment by inotia00** [comment]
This issue doesn't reproduce on my side, so I'm not sure if it's fixed.

Please patch with [revanced-patches-5.10.1-dev.4](https://github.com/inotia00/revanced-patches/releases/tag/v5.10.1-dev.4) and report back if the issue has been fixed.

You may also need to clear the RVX Manager cache.
