### ISSUE TITLE
bug(YouTube Music - Player components): Dismiss queue dismisses the miniplayer entirely

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [inotia00/ReVanced_Extended#3327]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

YouTube Music v8.30.54

### Bug description

Under normal circumstances, when the user taps `Dismiss queue`, the miniplayer goes behind the navigation bar and pops back up. But when including `Player components` patch and without even enabling  `Enable swipe to dismiss miniplayer`, the miniplayer, when using `Dismiss queue`, goes below the navigation bar, never to be seen again. Until a new song is played that is.

### Error logs

```shell

```

### Solution

Excluding `Player components` brings back the intended action.

### Additional context

Somehow,  without even enabling,`Enable swipe to dismiss miniplayer` is functioning when tapping `Dismiss queue`. This is just my hypothesis. 

### Acknowledgements

- [ ] This issue does not reproduce in the unpatched app.
- [x] This issue does not reproduce in the ReVanced version of the app.
- [x] This issue is not a duplicate of an [existing bug report](https://github.com/inotia00/ReVanced_Extended/labels/Bug%20report).
- [x] I did not use any settings marked as `Experimental flags`.
- [x] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] I have written the title and contents in English.

**Comment by inotia00** [comment]
This is an unpatched YouTube Music behavior.

Google has changed the miniplayer behavior in YouTube Music so strangely that I can't fix it.

Just don't use the Dismiss queue in the flyout menu.

(This is why I added the `Replace Dismiss queue menu` setting and the `Enable swipe to dismiss miniplayer` setting)

**Comment by ILoveOpenSourceApplications** [comment]
Actually no, this issue is only present on RVX Music. It's not there in stock YT Music or in ReVanced Music. I've tested all apps before opening this issue. 

YT Music:

https://github.com/user-attachments/assets/70276f30-c5ec-4d3f-a4a4-8c199bfde27c

RVX Music:

https://github.com/user-attachments/assets/3f03eb8a-ebe5-403e-8c61-108339fad517

**Comment by inotia00** [comment]
The implementation of the dismiss miniplayer behavior is quite complex, so some YouTube Music features are disabled regardless of the RVX Music setting.

The workaround is to simply exclude the `Player components` patch.

Or, If you modify the code and build the patch, you can also work around this by removing all code related to `Enable swipe to dismiss miniplayer`.

This is a prerequisite for implementing the `Enable swipe to dismiss miniplayer` patch, so the issue is still `Closed as not planned`.

**Comment by ILoveOpenSourceApplications** [comment]
Then, can you separate `Enable swipe to dismiss miniplayer` as its own patch and separate from `Player components` patch?

**Comment by ILoveOpenSourceApplications** [comment]
Or perhaps you can do what you did with `Hide fullscreen ads` patch. That's fine as well.

**Comment by inotia00** [comment]
I'll make a patch option for it if you want.

**Comment by inotia00** [comment]
btw `Hide fullscreen ads` patch option will be removed, as I fixed the side effect in YouTube Music.

**Comment by ILoveOpenSourceApplications** [comment]
> I'll make a patch option for it if you want.

That would be lovely. 

> btw `Hide fullscreen ads` patch option will be removed, as I fixed the side effect in YouTube Music.

That's also a great news. Happy to hear that!!!

**Comment by ILoveOpenSourceApplications** [comment]
With this change, I was able to test the miniplayer, when `Dismiss queue` is used, uses the color of the last song played with `Change miniplayer color` option turned on. This is also replicable in ReVanced. Is this something that is fixable or not?

**Comment by ILoveOpenSourceApplications** [comment]
Also, I think you forgot to remove the warning for `Hide fullscreen ads` in app description.
