### ISSUE TITLE
bug: Dislikes disappear when you scroll down

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#644]
### Type

Other

### Application

YouTube v18.12.35
ReVanced Patches v2.168.12

### Bug description

https://user-images.githubusercontent.com/127908708/230261701-68acba16-bcd9-47f2-b5ba-346cf8599b81.mp4

### Steps to reproduce

1. Play a video
2. Scroll down as you're watching the video

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Kuddus73** [comment]
@inotia00 The bug wasn't caused by watching the related shorts but by scrolling down, so I updated the title and the content of the report.

**Comment by NBruderman** [comment]
Can confirm I also have this bug

**Comment by jhon1282** [comment]
It happens sometimes even if you rotate the screen to landscape or then you go back to portrait.
The dislikes disappear

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.168.21](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.21)

**Comment by Kuddus73** [comment]
Now this is kinda hilarious.
The original reported bug now is happening (_Dislikes disappear when you watch related shorts of a video_).

Steps to reproduce:
1. Play a video
2. Play a related short **without closing the video**

**Comment by inotia00** [comment]
LOL I can't even guess what the cause of that issue is
Since it only occurs under very special conditions, it is expected that it will be very difficult to fix.

**Comment by Kuddus73** [comment]
Now, this is a legit bug which is still present in the app and might take a while to fix it.
So, I could open a new bug report or you can re-open this one with the correct title.

**Comment by inotia00** [comment]
Since the process of reproducing the bug is different from this one, please open a new separate issue
